---
title: "Model Outputs"
output: html_notebook
---
# Load Packages
```{r}
library(tidyverse)
library(sf)
library(sjPlot)
library(sjmisc)
library(stargazer)
library(lme4)
library(lmerTest)
library(sjPlot)
library(sjmisc)
library(ggplot2)

library(ggeffects)
library(performance)
library(R2MLwiN)
library(lmtest)
## Change path to MLwiN executable as appropriate:
options(MLwiN_path="/Users/shivyucel/Documents/projects/DPhil/Code_Data/mlwin/mlnscript")
```

# Notes
* Parks has the lowest number of observations, removing it leads to model convergence with 5/6 response variables
* Including HDI leads to no convergence, likely due to concentration of data in few adm1s
* Most viable option is including all responses without parks, and all independent variables except HDI


```{r}
# v12 is full model variables
#v17 is new demographic + popdens
mob_vars <- st_read('/Users/shivyucel/Documents/projects/DPhil/Code_Data/data/paper2/nigeria/THI_mobility_heat_w_vars_90_4SD_precip_Global2.csv')

#set up dependent variables
mob_vars$residential_difference <- as.numeric(mob_vars$residential_difference)
mob_vars$workplaces_difference <- as.numeric(mob_vars$workplaces_difference)
mob_vars$grocery_pharmacy_difference <- as.numeric(mob_vars$grocery_pharm_difference)
mob_vars$parks_difference <- as.numeric(mob_vars$parks_difference)
mob_vars$retail_difference <- as.numeric(mob_vars$retail_rec_difference)
mob_vars$transit_difference <- as.numeric(mob_vars$transit_difference)
mob_vars$adm1 <- as.factor(mob_vars$adm1)
mob_vars$adm2 <- as.factor(mob_vars$adm2)

mob_vars$month <- as.factor(mob_vars$month)

mob_vars$rain_standard_control <- as.numeric(mob_vars$rain_standard_control)
mob_vars$rain_standard_heat <- as.numeric(mob_vars$rain_standard_heat)
#set up independent variables

#level 1 variables
mob_vars$stage_frac <- as.numeric(mob_vars$stage_frac)

mob_vars$thi_heat <- as.numeric(mob_vars$thi_heat)
mob_vars$thi_centered <- mob_vars$thi_heat - mean(mob_vars$thi_heat)


mob_vars$thi_diff <- as.numeric(mob_vars$temp_diff)

mob_vars$HDI <- as.numeric(mob_vars$HDI)
mob_vars$popden_dec <- as.numeric(mob_vars$popden_dec)
mob_vars$HDI_dec <- as.numeric(mob_vars$HDI_dec)
mob_vars$over60_dec <- as.numeric(mob_vars$over60_dec)


mob_vars$weekend <- as.factor(mob_vars$weekend)

mob_vars$coast <- as.factor(mob_vars$coast)



mob_vars$temp_diff_centered <- as.numeric(mob_vars$temp_diff) - mean(mob_vars$temperature_2m_heat)

mob_vars$heatwave_dur <- as.factor(mob_vars$heatwave_dur)


```


```{r}
# Model 8: popden + coast
#CONVERGES

ng_model <- runMLwiN(c(residential_difference, workplaces_difference, grocery_pharmacy_difference, retail_difference) ~  
                       1 +
                       thi_centered + thi_diff + rain_standard_heat + rain_standard_control +
                       heatwave_dur + stage_frac + weekend +
                       HDI_dec + 
                       coast +
                       
                       (1|location) + (1|heat_ID) + (1|index) ,
                    data = mob_vars, D = "Multivariate Normal",estoptions = list(sort.force=TRUE, resi.store=TRUE, maxiter = 500)  )

```


```{r}
ng_model
```


# Try combinations which include HDI
```{r}
# removing grocery_pharm as a response 
# DOES NOT CONVERGE
model_24 <- runMLwiN(c(residential_difference, workplaces_difference, transit_difference, retail_difference) ~  
                       1 +
                       heat_temp_centered + temp_diff + 
                       early_hw + heatwave_dur + stage_frac + weekend +
                       HDI_dec +
                       
                       (1|location) + (1|heat_ID) + (1|index) ,
                    data = mob_vars, D = "Multivariate Normal",estoptions = list(sort.ignore=TRUE, resi.store=TRUE, maxiter = 30)  )
```

```{r}
# removing grocery_pharm and transit as a response 
# DOES NOT CONVERGE
model_24 <- runMLwiN(c(residential_difference, workplaces_difference, retail_difference) ~  
                       1 +
                       heat_temp_centered + temp_diff + 
                       early_hw + heatwave_dur + stage_frac + weekend +
                       HDI_dec +
                       
                       (1|location) + (1|heat_ID) + (1|index) ,
                    data = mob_vars, D = "Multivariate Normal",estoptions = list(sort.ignore=TRUE, resi.store=TRUE, maxiter = 30)  )
```

```{r}
#removing grocery_pharm, retail, parks
#CONVERGES
model_24 <- runMLwiN(c(residential_difference, workplaces_difference, transit_difference) ~  
                       1 +
                       heat_temp_centered + temp_diff + 
                       early_hw + heatwave_dur + stage_frac + weekend +
                       HDI_dec +
                       
                       (1|location) + (1|heat_ID) + (1|index) ,
                    data = mob_vars, D = "Multivariate Normal",estoptions = list(sort.ignore=TRUE, resi.store=TRUE, maxiter = 30)  )
```


```{r}
summary(ng_model)
```

```{r}
x <- data.frame(ng_model@FP)

write.csv(x, file='/Users/shivyucel/Documents/projects/DPhil/Code_Data/data/regression/THI_nigeria_params_4SD_precip_sort_v1_G2.csv')
```



